---
mainfont: PragmataPro
output:
  - html_document
---

<style>
h1 { /* Header 1 */
  font-size: 25px;
  color: #181818;

}
table, th, td {
  border: 1px solid #181818;
  border-collapse: collapse;
  vertical-align: top;
  font-size : 15px;
  padding : 20px;
}
p{
  font-size : 10px;
  margin : 0px;
}
</style>
<!--body {text-align: justify}-->

# Business Model Canvas

<table>
<tr>
<td rowspan="2">
<b>Key Partners</b>
<p>&nbsp;

**Advertiser**<br>
*Advertisement agencies.*<br>
<br>
**Content maker**<br>
*Journalist, News aggregator.*<br>
<br>
**Social media**<br>
*Instagram, Facebook, Twitter.*<br>

</p>
</td>
<td>
<b>Key Activities</b>
<p>&nbsp;

**Create** *content for consumption.*<br>
**Edit** *content that have been posted.*<br>
**Discoverable** *through search engine.*<br>
**Development** *using feedback from audience.*<br>
 
</p>
</td>
<td rowspan="2" colspan="2">
<b>Value Propositions</b>
<p>&nbsp;

**Advertiser**<br>
*Subscription based plan.*<br>
*Newsletter and promotion.*<br>
<br>
**Audience**<br>
*Entertainment content.*<br>

</p>
</td>
<td>
<b>Customer Relationships</b>
<p>&nbsp;

**Advertiser**<br>
*Feedback from audience.*<br>
<br>
**Audience**<br>
*Add suggestions for contents.*<br>

</p>
</td>
<td rowspan="2">
<b>Customer Segments</b>
<p>&nbsp;

**Advertiser**<br>
∙ *Social Media based Ads.*<br>
∙ *Online shop based Ads.*<br>
<br>
**Audience**<br>
∙ *Indonesians*<br>
∙ *Global audience.*<br>

</p>
</td>
</tr>
<tr>
<td>
<b>Key Resources</b>
<p>&nbsp;

**Human Resources**<br>
*Aggregator of contents.*<br>
<br>
**Intellectual Property**<br>
*Copyright for content creator.*<br>

</p>
</td>
<td>
<b>Channels</b>
<p>&nbsp;

**Advertiser**<br>
*Adevertisement agencies.*<br>
<br>
**Audience**<br>
*Social media integration.*<br>


</p>
</td>
</tr>
<tr>
<td colspan="3">
<b>Cost Structure</b>
<p>&nbsp;

**Salary**<br>
*Per month for workers.*<br>
<br>
**IT Infrastructure**<br>
*Infrastructure cost.*
<br>
**Promotion and Marketing**<br>
*Social media and subscription plan.*<br>
<br>

</p>
</td>
<td colspan="3">
<b>Revenue Streams</b>
<p>&nbsp;

**Digital Advertisement**<br>
*Advertisement on-site.*<br>
<br>
**Partnership**<br>
*Content aggregator.*<br>

</p>
</td>
</tr>
</table>
<br>
Inspired by : https://www.researchgate.net/publication/333754705_BUSINESS_MODEL_FORMULATION_FOR_E-NEWSPAPER_IN_INDONESIA_CASE_STUDY_PIKIRAN_RAKYAT
